services:
  - type: web
    name: splendor-web
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://ostrichick.github.io,https://splendor-web-yrrr.onrender.com
